Third lab
simmaksim/Itirod pull request #2
Opened 2022-04-29 21:52 UTC by simmaksim

0:51 - третий бокал...

2022-04-29 22:05 UTC, simmaksim commented
https://simmaksim.github.io/Itirod/

2022-05-04 10:15 UTC, Nastik1811 commented
Мне эта часть не нравится. Всё слиплось 
<img width="259" alt="image" src="https://user-images.githubusercontent.com/37243282/166662252-287fff9f-fd63-409c-b8ed-6287ab6bc1d4.png">

2022-05-04 10:16 UTC, Nastik1811 commented
тут остались маркеры от li (кружочки)
<img width="24" alt="image" src="https://user-images.githubusercontent.com/37243282/166663192-e45fe188-bcd4-47d5-a5ec-3b24a4e03b74.png">

2022-05-04 10:17 UTC, Nastik1811 commented
Внутренние отступы добавь тут тоже
<img width="131" alt="image" src="https://user-images.githubusercontent.com/37243282/166663322-510509db-59a1-4d0e-ba93-bc49ffaee98a.png">

2022-05-04 10:18 UTC, Nastik1811 commented
Лучше с плейлистами сделать так, как у спотифая, чтобы когда не влазит обрезать с многоточием (заодно узнаешь, как это сделать)

2022-05-04 10:45 UTC, Nastik1811 requested changes
<img width="503" alt="Screenshot 2022-05-04 at 13 45 15" src="https://user-images.githubusercontent.com/37243282/166667179-aaaa66bd-5761-475c-888f-c897dda3eb85.png">

2022-05-04 10:45 UTC, Nastik1811 commented on index.html
> +                    <li class="nav-item"><a onclick="onButtonClick('home')">
в следующей лабе тут не должно быть `onclick`

2022-05-04 10:45 UTC, Nastik1811 commented on index.html
> +                    <li class="playlist-item"><a style="font-family: monospace">Playlist 1</a></li>
никаких inline-стилей

2022-05-04 10:45 UTC, Nastik1811 commented on index.html
> +                        <p style="color: #a7a9be">Author</p>
😠

2022-05-04 10:45 UTC, Nastik1811 commented on index.html
> +                    <button class="foot-btn" aria-label="Слушать" data-testid="control-button-playpause" style="--button-size:32px;"><svg role="img" height="16" width="16" viewBox="0 0 16 16" class="
`style="--button-size:32px;"` а это что такое?

2022-05-04 10:45 UTC, Nastik1811 commented on index.html
> +                <form role="search"><input class="line-locat ebHsEf QO9loc33XC50mMRUCIvf" maxlength="800" autocorrect="off" autocapitalize="off" spellcheck="false" placeholder="Исполнитель, трек или
Кто-то обещал убрать нечитаемые имена классов 

> `ebHsEf QO9loc33XC50mMRUCIvf`

2022-05-04 10:45 UTC, Nastik1811 commented on login_style.css
> +    height: 100vh;
`100vh` не используем

2022-05-04 10:45 UTC, Nastik1811 commented on main_style.css
> +.NavigSearch {
А что за микс всевозможных стилей написания имён? 👀 
`.NavigSearch`
`.search-icon`
`.playlist_and_name_container`
`.Like-btn`

2022-05-04 10:45 UTC, Nastik1811 commented on main_style.css
> +.NavigSearch {
`.search-icon` правильный, если что

2022-05-04 23:19 UTC, simmaksim commented on index.html
> +                    <li class="playlist-item"><a style="font-family: monospace">Playlist 1</a></li>
done

2022-05-04 23:25 UTC, simmaksim commented on index.html
> +                        <p style="color: #a7a9be">Author</p>
done

2022-05-04 23:28 UTC, simmaksim commented on index.html
> +                    <button class="foot-btn" aria-label="Слушать" data-testid="control-button-playpause" style="--button-size:32px;"><svg role="img" height="16" width="16" viewBox="0 0 16 16" class="
fixed

2022-05-04 23:31 UTC, simmaksim commented on index.html
> +                <form role="search"><input class="line-locat ebHsEf QO9loc33XC50mMRUCIvf" maxlength="800" autocorrect="off" autocapitalize="off" spellcheck="false" placeholder="Исполнитель, трек или
этот момент я пофиксил. Я убрал все нечитаемые имена классов, которые лежат в .css. А те классы, который в кнопках из спотика, но при это никак не юзались мной я не трогал

2022-05-04 23:39 UTC, simmaksim commented on main_style.css
> +.NavigSearch {
fixed

2022-05-04 23:51 UTC, simmaksim commented on login_style.css
> +    height: 100vh;
fixed

2022-05-05 00:15 UTC, simmaksim commented on index.html
> +                    <li class="playlist-item"><a style="font-family: monospace">Playlist 1</a></li>
почистил весь код, убрал или заменил инлайн стили

2022-05-05 04:36 UTC, Nastik1811 commented
Отступы внутри рекомендаций забыл добавить))

2022-05-05 04:48 UTC, Nastik1811 approved these changes
Ладно, засиделись с вёрсткой. Давайте двигаться дальше

![0kqbsji989h81](https://user-images.githubusercontent.com/37243282/166864908-ef2a46ac-1a7e-4bde-b270-1509c40376fd.jpeg)

2022-05-05 20:39 UTC, merged